set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'robhurring/tmux-uptime'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin '0xAF/tmux-public-ip'
set-option -g @plugin 'b0o/tmux-autoreload'

set-option -g status on
set-option -g status-bg black
set-option -g status-fg white
set-option -g status-interval 30
set -g status-justify centre

set -g base-index 1
set -g pane-base-index 1

# set -g window-style bg=colour232
set -g window-style bg=colour233
set -g window-status-style bg=colour236,fg=blue
set -g window-status-current-style bg=blue,fg=black
set -g window-status-format " #I:#W "
set -g window-status-current-format " #[bold]#I:#W* "

set -g @batt_icon_status_charged '·'
set -g @batt_icon_status_charging '↑'
set -g @batt_icon_status_discharging '↓'

set -g status-left-length 85
set -g status-left "#[bg=yellow,fg=black] #I:#P "
set -ag status-left "#[bg=purple,fg=white] #{uptime} "  
set -ag status-left "#[bg=red,fg=white] #{public_ip} "

set -g status-right-length 60
set -g status-right "#[bg=black,fg=white] #{battery_icon_status} #{battery_percentage} | %H:%M | %d-%b "
# set -g status-right "#[bg=black,fg=white] %H:%M:%S | %d-%b "
set -ag status-right "#[bg=red,fg=white] #(whoami) "
set -ag status-right "#[bg=white,fg=black] #h "

run '~/.tmux/plugins/tpm/tpm'
